apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: yandex-allInOne
spec:
  network: 
    order: 100
    type: terraform
    path: file://network
    name: "{{ .alias }}"
  subnet:
    order: 110
    type: terraform
    path: file://subnet
    network: "{{ .network.name   }}"
    zone:    "{{ .target.spec.terraform.zone }}"
    name:    "{{ .alias }}"
  cluster:
    order: 120
    type: terraform
    path: file://cluster
    network: "{{ .network.name   }}"
    subnet:  "{{ .subnet.name    }}"
    zone: "{{ .target.spec.terraform.zone }}"
    name: "{{ .alias }}"
    assign_public_ip: true
  user:
    order: 130
    type: terraform
    path: file://user
    name:     "{{ .alias }}"
    password: fdmfkmMKMOOcokdsmpcvskd  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    cluster:  "{{ .cluster.name  }}"
  database:
#script setting
    order: 1000
    type: terraform
    path: file://database
    alias: ""
#script input
    cluster: "{{ .cluster.name  }}"
    user:    "{{ .user.name     }}"
    name:    "{{ .alias }}-database"
#script output mapping
    outputMapping:
      host:     "c-{{ .input.cluster.id }}.rw.mdb.yandexcloud.net"
      port:     6432
      database: "{{ .name }}"
      user:     "{{ .user }}"
      password: "{{ .input.user.password }}"
      sslmode:     verify-full
      ssl_ca_file: '{{ .Files.Get "resources/postgresql/yandex/database/ssl_ca_file.crt" }}'
