apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: postgresql
spec:
  install:
    # resource: postgresql
    # version:  yandex
    # name:     allInOne
    # alias:    ""

    resource: postgresql
    version:  kubernetes
    name:     bitnami-15.1.0--standalone16.2
    alias:    ""
