apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.alias }}-deployment
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/config"
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ include "service.fullname" . }}
