apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: postgresql
spec:
  script:
    type: helm
    name: postgresql                                # определяется в template
    repository: https://charts.bitnami.com/bitnami  # определяется в template
    version:          "15.1.0"                      # определяется в template
    fullnameOverride: "{{ .alias }}"   # локально "{{ .alias }}" , в яндексе, что получится
    auth:
      database:         "{{ .alias }}" # сохранять
      username:         servicea-user  # сохранять, генериться из parent aleas, или rnd
      password:         HOrFk14CyX     # сохранять, генериться rnd
      postgresPassword": xxdsdsddsxxxx # сохранять, генериться из parent aleas, или rnd
    outputMapping:
      hostname: "{{ .context.fullnameOverride }}"
      database: "{{ .context.auth.database }}"
      username: "{{ .context.auth.username }}"
      password: "{{ .context.auth.password }}"
