apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceB
spec:
  dependencies:
    # build:
    #   type: job
    # shared-db-between-services:
    #   root: true
    #   resource: postgresql
    #  s3:
    postgresql:
      type: helm
      repository: file://../helm
      values:
        
  # script:
  #   type: helm
  #   repository: file://../helm
  #   image: "__deployto-lookup: build.image"
  #   my-database: "__deployto-lookup: build.image"
  #   shared-db: "__deployto-lookup: shared-db-between-services.ConnectionString"
