apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceB
spec:
  dependencies:
  - kind: postgresql
    name: only4b
  - kind: postgresql
    name: shared-db-between-services
    root: true
  - kind: s3