apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceB
spec:
  dependencies:
    build:
      script:
        type: job
    only4b:
      script:
        type: template
        values:
          name: postgresql
    shared-db-between-services:
      root: true
      script:
        type: template
        values:
          name: postgresql
    s3:
  script:
    type: helm
    values:
      repository: file://../helm
      build:
        image: deployto-lookup build.image