apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceB
spec:
  dependencies:
    # build:
    #   type: job
    # shared-db-between-services:
    #   root: true
    #   resource: postgresql
    #  s3:
    postgresql:
      type: helm
      repository: https://charts.bitnami.com/bitnami
      name:             postgresql
      version:          "15.1.0"
      fullnameOverride: postgresql-standalone
      auth:
        database:         servicea-db
        username:         servicea-user
        password:         HOrFk14CyX
        postgresPassword": xxdsdsddsxxxx
        
  # script:
  #   type: helm
  #   repository: file://../helm
  #   image: "__deployto-lookup: build.image"
  #   my-database: "__deployto-lookup: build.image"
  #   shared-db: "__deployto-lookup: shared-db-between-services.ConnectionString"
