apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceB
spec:
  dependencies:
    # build:
    #   type: job
    #  s3:
    # postgresql:
    #   type: helm
    #   repository: https://charts.bitnami.com/bitnami
    #   version:          "15.1.0"
    #   fullnameOverride: postgresql-standalone
    #   auth:
    #     database:         servicea-db
    #     username:         servicea-user
    #     password:         HOrFk14CyX
    #     postgresPassword": xxdsdsddsxxxx
    shared-db-between-services:
      type: helm
      root: true
      repository: https://charts.bitnami.com/bitnami  # определяется в template
      version:          "15.1.0"                      # определяется в template
      fullnameOverride: "{{ .alias }}"   # локально "{{ .alias }}" , в яндексе, что получится
      auth:
        database:         "{{ load | .alias  | rnd 12 34}}" # сохранять
        username:         servicea-user  # сохранять, генериться из parent aleas, или rnd
        password:         HOrFk14CyX     # сохранять, генериться rnd
        postgresPassword": xxdsdsddsxxxx # сохранять, генериться из parent aleas, или rnd
      outputMapping:
        hostname: "{{ .fullnameOverride }}"
        username: "{{ .auth.username }}"
  # script:
  #   type: helm
  #   repository: file://../helm
  #   image: "__deployto-lookup: build.image"
  #   my-database: "__deployto-lookup: build.image"
  #   shared-db: "__deployto-lookup: shared-db-between-services.ConnectionString"
