apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceB
spec:
  dependencies:
  - name: postgresql
    alias: only4b
  - name: postgresql
    alias: shared-db-between-services
    root: true
  - name: s3