apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.alias }}-deployment
  labels:
    app: {{ .Values.alias }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.alias }}
  template:
    metadata:
      labels:
        app: {{ .Values.alias }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ci.build.REGISTRY }}/{{ .Values.ci.build.APPLICATION_NAME }}:{{ .Values.ci.build.COMMITSHORT }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: config
            mountPath: "/config/postgresql.yaml"
            subPath: "postgresql.yaml"
      volumes:
        - name: config
          configMap:
            name: {{ .Values.alias }}-configmap
            items:
            - key: "postgresql.yaml"
              path: "postgresql.yaml"

