apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.alias }}-deployment
  labels:
    app: nginx
spec:
  selector:
    label: {{ .Values.alias }}-deployment
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/config"
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Values.name }}