apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceA
spec:
  dependencies:
    build:
      script:
        type: job    # если values.name  не установлен, то использовать alias
    service-b:
      script:
        type: component
        values:
#          repository: https://rep-service-b/service-b.git
          path: ../../service-b
    postgresql:
    shared-db-between-services:
      root: true
      script:
        type: template
        values:
          name: postgresql
    s3:
      script:
        type: template
        values:
          name: s3/ha
  script:
    type: helm
    values:
      repository: file://../helm
      build:
        image: deployto-lookup build.image