apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceA
spec:
  dependencies:
  - kind: component
    name: service-b
    repository: https://rep-service-b/service-b.git
  - kind: postgresql
  - kind: postgresql
    name: shared-db-between-services
    root: true
  - kind: s3
    name: serviceA-for-s3
