apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceA
spec:
  dependencies:
    build:
      type: job    # если values.name  не установлен, то использовать alias
    service-b:
      type: component
#      repository: https://rep-service-b/service-b.git
      path: ../../service-b
    postgresql:
    shared-db-between-services:
      root: true
      name: postgresql
    s3:
      name: s3/ha
  script:
    type: helm
    repository: file://../helm
    build:
      image: "__deployto-lookup: build.image"
    shared-db: "__deployto-lookup: shared-db-between-services.ConnectionString"
    s3: "__deployto-lookup: s3.ConnectionString"