apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: FullApplication
spec:
  dependencies:
    service-a:
      type: component
      root: true
      path: ../service-a
  # script:
  # TODO helm with ingress