apiVersion: deployto.dev/v1beta1
kind: Environment
metadata:
  name: local
spec:
  defaulTemplate: prod
  targets:
    - local-target
---
apiVersion: deployto.dev/v1beta1
kind: Target
metadata:
  name: local-target
spec:
  defaulTemplate: prod
  values:
    type: Helm