apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: example01
spec:
  ci:
    type: job
    path: ..
  postgresql:
    auth:
      username:         servicea-user
      password:         HOrFk14CyX
      postgresPassword: xxdsdsddsxxxx
  install:
    alias: ""
    order: 1000
    type: helm
    path: ../helm
