apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: example01
spec:
  # dependencies:
  #   ci:
  #     type: job
  #     path: ..
  #   postgresql:
  script:
    type: helm
    path: ../helm
