apiVersion: deployto.dev/v1beta1
kind: Job
metadata:
  name: ci
spec:
  steps:
    - name: build
      run: |
        docker build --tag ${DOCKER_REGISTRY}/${APPLICATION_NAME}:${COMMITSHORT} -f ${DOCKERFILE} .
        docker tag ${DOCKER_REGISTRY}/${APPLICATION_NAME}:${COMMITSHORT} ${DOCKER_REGISTRY}/${APPLICATION_NAME}:${TAG}
        docker tag ${DOCKER_REGISTRY}/${APPLICATION_NAME}:${COMMITSHORT} ${DOCKER_REGISTRY}/${APPLICATION_NAME}:latest
      env:
        DOCKER_REGISTRY:  deployto
        APPLICATION_NAME: "{{ .component }}"
        TAG:         "{{ .git.Tag }}"
        COMMITSHORT: "{{ .git.CommitShort }}"
        DOCKERFILE: "../dockerfile"
    - name: push
      continue-on-error: true
      run: |
        minikube image rm ${DOCKER_REGISTRY}/${APPLICATION_NAME}:${COMMITSHORT} && minikube image load ${DOCKER_REGISTRY}/${APPLICATION_NAME}:${COMMITSHORT} 
        minikube image rm ${DOCKER_REGISTRY}/${APPLICATION_NAME}:latest && minikube image load ${DOCKER_REGISTRY}/${APPLICATION_NAME}:latest
      env:
        DOCKER_REGISTRY:  deployto
        APPLICATION_NAME: "{{ .component }}"
        COMMITSHORT: "{{ .git.CommitShort }}"
