apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alias }}-config
data:
  postgresql.yaml: | 
    host:     {{ .Values.postgresql.host     }}
    port:     {{ .Values.postgresql.port     }}
    database: {{ .Values.postgresql.database }}
    user:     {{ .Values.postgresql.user     }}
    password: {{ .Values.postgresql.password }} 

{{ if hasKey .Values.postgresql "ssl_ca_file" }}
  ssl_ca.crt:  |
{{ .Values.postgresql.ssl_ca_file | indent 4 }}
{{ end }}
