apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.alias }}-deployment
  labels:
    app: {{ .Values.alias }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.alias }}
  template:
    metadata:
      labels:
        app: {{ .Values.alias }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
          volumeMounts:
          - name: config
            mountPath: "/config"
      volumes:
        - name: config
          configMap:
            name: {{ .Values.alias }}-config
