apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: example01
spec:
  ci:
    type: job
    path: ..
  postgresql:
  install:
    alias: ""
    order: 1000
    type: helm
    path: ../helm
    image: "{{ .ci.build.REGISTRY }}/{{ .ci.build.APPLICATION_NAME }}:{{ .ci.build.COMMITSHORT }}"
