apiVersion: deployto.dev/v1beta1
kind: Environment
metadata:
  name: prod
spec:  
  targets:
  - prod-target
---
apiVersion: deployto.dev/v1beta1
kind: Target
metadata:
  name: prod-target
spec:
  namespace: test
  kubeconfig:
    filename: prod/kubeconfig
  terraform:
    provider: yandex
    path: "file://SERVER/target/local-target-ya-cloud/"
    env: 
      YC_ZONE: "ru-central1-d"
      YC_TOKEN: "t1.9euelZqei5eUm8fOiZiYiZXKnY-Kju3rnpWayZeNnpuXjpuWjJWNkpOZjInl8_dNXAVO-e8aHSdN_N3z9w0LA0757xodJ038zef1656Vmp7GyZGayImMl8eWj46SyZGL7_zN5_XrnpWalYmQzpCczJ2PiZbJkZqWiorv_cXrnpWansbJkZrIiYyXx5aPjpLJkYs.vnTrvH1R705ZQWRpW0becelwv1eflb2OYlv6_qhgIzDXTi2VdITjK6KUOfuSmB3ffJ0sHK0IqOa6EKa86rhVAg"
      YC_CLOUD_ID: "b1g8o6pkacilvmta12t9"
      YC_FOLDER_ID: "b1gdqo93r75d249hlicn"