apiVersion: deployto.dev/v1beta1
kind: Environment
metadata:
  name: prod
spec:  
  targets:
  - prod-target
  pacth:
    postgresql:
      resource: postgresql
      version:  yandex
      name:     allInOne
---
apiVersion: deployto.dev/v1beta1
kind: Target
metadata:
  name: prod-target
spec:
  kubeconfig:
    namespace: test
    filename: secrets/kubeconfig
  terraform:
    zone:      "ru-central1-d"
    token:     "{{ .secrets.terraform.token     }}"
    cloud_id:  "{{ .secrets.terraform.cloud_id  }}"
    folder_id: "{{ .secrets.terraform.folder_id }}"
