apiVersion: deployto.dev/v1beta1
kind: Job
metadata:
  name: 'Link Checker: All English'
spec:
  steps:
    - name: Hello World step
      run: |
        echo "Hello World step 1.2"
        make build
    - name: Hello World step 2
      run: |
        make push