apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: serviceA
spec:
  dependencies:
  - name: service-b
    repository: https://rep-service-b/service-b.git
    version: "1.2.3"
  - name: postgresql
    alias: postgresql-for-a
    input:   
      install_to: shared
      replicatuion: 
        true
  - name: s3
    alias: s3-for-a
  script:
    repository: file://../helm/
    type: helm
    input:
       db_name:  $postgresql-for-a.dbname
       log_level:    
//	  output:

     