apiVersion: deployto.dev/v1beta1
kind: Component
metadata:
  name: servicea
spec:
  dependencies:
    db1:
      type: terraform
      name: postgresql  
      path: file:///..//terraform-db/               
      # TODO git clone repository
      #repository: https://git.host/resources/postgresql/v12  # определяется в template
      version:          "12"                      # определяется в template
      fullnameOverride: "{{ .alias }}"   # локально "{{ .alias }}" , в яндексе, что получится
      auth:
        database:         "{{ .alias }}" # сохранять
        username:         test-user  # сохранять, генериться из parent aleas, или rnd
        password:         test-password     # сохранять, генериться rnd
      outputMapping:
        hostname: "{{ .context.fullnameOverride }}"
        database: "{{ .context.auth.database }}"
        username: "{{ .context.auth.username }}"
        password: "{{ .context.auth.password }}"
    db2:
      type: terraform
      name: postgresql  
      path: file:///..//terraform-db/               
      # TODO git clone repository
      #repository: https://git.host/resources/postgresql/v12  # определяется в template
      version:          "12"                      # определяется в template
      fullnameOverride: "{{ .alias }}"   # локально "{{ .alias }}" , в яндексе, что получится
      auth:
        database:         "{{ .alias }}" # сохранять
        username:         test-user-2  # сохранять, генериться из parent aleas, или rnd
        password:         test-password     # сохранять, генериться rnd
      outputMapping:
        hostname: "{{ .context.fullnameOverride }}"
        database: "{{ .context.auth.database }}"
        username: "{{ .context.auth.username }}"
        password: "{{ .context.auth.password }}"
    
