name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: terraformrc
        run: cp .terraformrc ~/.terraformrc
      - name: Test with the Go CLI
        run: go test -timeout 30m ./...
        env: 
          TF_VAR_YC_CLOUD_ID: ${{ secrets.TF_VAR_YC_CLOUD_ID }}
          TF_VAR_YC_FOLDER_ID: ${{ secrets.TF_VAR_YC_FOLDER_ID }}
          TF_VAR_YC_TOKEN: ${{ secrets.TF_VAR_YC_TOKEN }}